name: CI

on: [push]

jobs:
  phpunit:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        php-version: ['7.4']
    name: 'PHPUnit - PHP/${{ matrix.php-version }} - OS/${{ matrix.os }}'
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, intl
          coverage: xdebug
          ini-values: xdebug.max_nesting_level=2048
      - name: Install Dependencies
        run: composer install --no-progress
      - name: PHPUnit
        run: vendor/bin/phpunit --coverage-clover=coverage.clover
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
  psalm:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['7.4']
    name: 'Psalm - PHP/${{ matrix.php-version }}'
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, intl
      - name: Install Dependencies
        run: composer install --no-progress
      - name: Psalm
        run: vendor/bin/psalm --shepherd
